name: Build EXE

on:
  push:
    branches: [ "main" ]  # 当你提交代码到 main 分支时触发

jobs:
  build:
    runs-on: windows-latest  # 必须在 Windows 环境下打包

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pynput pygetwindow pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --noconsole --onefile --clean --name "Google_Scanner_V5.7" V1.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Google_Scanner_EXE
        path: dist/Google_Scanner_V5.7.exe
